/**
 * Mock data for demo mode — used when Supabase is not configured.
 * Provides realistic sample data for all screens.
 */
import type { Craving, Match, Conversation, Message, UserProfile } from "@/types";

export const mockCurrentUser: UserProfile = {
  id: "user-1",
  name: "You",
  email: "you@eatchat.com",
  avatar_url: undefined,
  bio: "Food lover & adventure seeker 🍕✈️",
  food_preferences: ["pizza", "sushi", "tacos", "ramen"],
  location: { latitude: 40.7128, longitude: -74.006, city: "New York" },
  created_at: "2024-01-15T10:00:00Z",
  updated_at: "2024-06-01T12:00:00Z",
};

export const mockUsers: UserProfile[] = [
  {
    id: "user-2",
    name: "Sarah M.",
    email: "sarah@example.com",
    avatar_url: undefined,
    bio: "NYC foodie exploring every corner 🗽",
    food_preferences: ["ramen", "sushi", "thai"],
    location: { latitude: 40.7282, longitude: -73.7949, city: "New York" },
    created_at: "2024-02-10T10:00:00Z",
    updated_at: "2024-05-20T12:00:00Z",
  },
  {
    id: "user-3",
    name: "James K.",
    email: "james@example.com",
    avatar_url: undefined,
    bio: "Always hungry, never bored 🌮",
    food_preferences: ["tacos", "bbq", "burger"],
    location: { latitude: 40.758, longitude: -73.9855, city: "New York" },
    created_at: "2024-03-05T10:00:00Z",
    updated_at: "2024-06-01T12:00:00Z",
  },
  {
    id: "user-4",
    name: "Priya R.",
    email: "priya@example.com",
    avatar_url: undefined,
    bio: "Spice queen 🌶️ curry enthusiast",
    food_preferences: ["indian", "thai", "bbq"],
    location: { latitude: 40.7484, longitude: -73.9857, city: "New York" },
    created_at: "2024-01-28T10:00:00Z",
    updated_at: "2024-05-15T12:00:00Z",
  },
];

export const mockCravings: Craving[] = [
  {
    id: "craving-1",
    user_id: "user-2",
    user: mockUsers[0],
    food_type: "ramen",
    food_category: "ramen",
    description: "Craving some tonkotsu ramen after work! Anyone want to hit up Ippudo?",
    photo_url: undefined,
    location: { latitude: 40.7282, longitude: -73.7949, city: "New York" },
    expiry: "4h",
    expires_at: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: "craving-2",
    user_id: "user-3",
    user: mockUsers[1],
    food_type: "tacos",
    food_category: "tacos",
    description: "Taco Tuesday should be every day. Who's in? 🌮",
    photo_url: undefined,
    location: { latitude: 40.758, longitude: -73.9855, city: "New York" },
    expiry: "24h",
    expires_at: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "craving-3",
    user_id: "user-4",
    user: mockUsers[2],
    food_type: "butter chicken",
    food_category: "indian",
    description: "Need my fix of good Indian food. Tandoori or bust!",
    photo_url: undefined,
    location: { latitude: 40.7484, longitude: -73.9857, city: "New York" },
    expiry: "1h",
    expires_at: new Date(Date.now() + 60 * 60 * 1000).toISOString(),
    is_active: true,
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: "craving-4",
    user_id: "user-2",
    user: mockUsers[0],
    food_type: "sushi",
    food_category: "sushi",
    description: "Omakase date? Splitting a omakase set would be amazing rn 🍣",
    photo_url: undefined,
    location: { latitude: 40.73, longitude: -73.99, city: "New York" },
    expiry: "4h",
    expires_at: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    created_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: "craving-5",
    user_id: "user-3",
    user: mockUsers[1],
    food_type: "pizza",
    food_category: "pizza",
    description: "Late night pizza run? I know a spot with the best margherita 🍕",
    photo_url: undefined,
    location: { latitude: 40.76, longitude: -73.97, city: "New York" },
    expiry: "1h",
    expires_at: new Date(Date.now() + 60 * 60 * 1000).toISOString(),
    is_active: true,
    created_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
];

export const mockMatches: Match[] = [
  {
    id: "match-1",
    craving_id: "craving-1",
    craving: mockCravings[0],
    matched_user: mockUsers[0],
    status: "accepted",
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "match-2",
    craving_id: "craving-2",
    craving: mockCravings[1],
    matched_user: mockUsers[1],
    status: "accepted",
    created_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "match-3",
    craving_id: "craving-3",
    craving: mockCravings[2],
    matched_user: mockUsers[2],
    status: "pending",
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockConversations: Conversation[] = [
  {
    id: "conv-1",
    match: mockMatches[0],
    participants: [mockCurrentUser, mockUsers[0]],
    last_message: {
      id: "msg-1",
      conversation_id: "conv-1",
      sender_id: "user-2",
      content: "Ippudo at 7pm works! Can't wait 🍜",
      created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    },
    unread_count: 2,
    updated_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: "conv-2",
    match: mockMatches[1],
    participants: [mockCurrentUser, mockUsers[1]],
    last_message: {
      id: "msg-2",
      conversation_id: "conv-2",
      sender_id: "user-1",
      content: "Tacos were amazing! Same time next week? 🌮",
      created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    unread_count: 0,
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockMessages: Message[] = [
  {
    id: "msg-10",
    conversation_id: "conv-1",
    sender_id: "user-2",
    content: "Hey! So you're craving ramen too? 😄",
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-11",
    conversation_id: "conv-1",
    sender_id: "user-1",
    content: "Absolutely! Tonkotsu is the best. Know any good spots?",
    created_at: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-12",
    conversation_id: "conv-1",
    sender_id: "user-2",
    content: "Ippudo on 4th Ave is incredible. They have the richest broth 🍜",
    created_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-13",
    conversation_id: "conv-1",
    sender_id: "user-1",
    content: "I've heard great things! When are you free?",
    created_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-14",
    conversation_id: "conv-1",
    sender_id: "user-2",
    content: "Tonight at 7pm?",
    created_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-15",
    conversation_id: "conv-1",
    sender_id: "user-1",
    content: "Perfect! See you there 👍",
    created_at: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-1",
    conversation_id: "conv-1",
    sender_id: "user-2",
    content: "Ippudo at 7pm works! Can't wait 🍜",
    created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
];
